#!/bin/bash

podman exec -e PS1='\[\e[1m\][\[\e[0;92m\]\u\[\e[0m\]@\[\e[92m\]\H\[\e[0;1m\]]-[\[\e[0;96m\]\W\[\e[0;1m\]]\[\e[0m\]\\$ ' --user "$subsys_user_uid:$subsys_user_gid" -it subsystem /bin/bash -c "cd /home/$subsys_user && exec /bin/bash"