#!/bin/bash

subsys_user=""
subsys_user_uid=""
subsys_user_gid=""

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --subsys-user=*)
            subsys_user="${1#*=}"
            ;;
        --subsys-user-uid=*)
            subsys_user_uid="${1#*=}"
            ;;
        --subsys-user-gid=*)
            subsys_user_gid="${1#*=}"
            ;;
        *)
            echo "Unknown args"
            exit 1
            ;;
    esac
    shift
done

if [ -z "$subsys_user" ] || [ -z "$subsys_user_uid" ] || [ -z "$subsys_user_gid" ]; then
    echo "Error: Missing required arguments"
    exit 1
fi

podman exec -e PS1='\[\e[1m\][\[\e[0;92m\]\u\[\e[0m\]@\[\e[92m\]\H\[\e[0;1m\]]-[\[\e[0;96m\]\W\[\e[0;1m\]]\[\e[0m\]\\$ ' --user "$subsys_user_uid:$subsys_user_gid" -it subsystem /bin/bash -c "cd /home/$subsys_user && exec /bin/bash"