#!/bin/bash

set -e pipefail

if [[ $EUID -eq 0 ]]; then
    echo "Running as root. Abort."
    exit 1
elif [[ -d /var/usrlocal/transit/varhome/"$USER"/Desktop ]]; then
    echo "Fixing $USER's home directory..."
    touch /tmp/.transit-fix/$(basename $HOMEDIR)
    rm -f "$HOME"/README.md
    echo "Changes not applied yet."
    echo "Log out and back in to apply changes."
else
    echo "No issues found."
fi
