#!/bin/bash

set -euo pipefail

IMAGE_FILE=/usr/local/share/containers/default.container

if ! podman container exists $CONTAINER_NAME; then
  LOAD_OUTPUT=$(podman load < $IMAGE_FILE)
  IMAGE=$(echo "$LOAD_OUTPUT" | grep -o 'localhost/[^:]*:[^ ]*')
  podman create --name subsystem -v /var/home:/home:Z $IMAGE
fi

podman start subsystem