#!/bin/bash

set -euo pipefail

mkdir -p /var/usrlocal/nixfs/{upper,work}
chown root:root /var/usrlocal/nixfs/{upper,work}
chmod 700 /var/usrlocal/nixfs/{upper,work}

semanage fcontext -a -t etc_t "/usr(/local/nixfs/upper)?/nix/store/[^/]+/etc(/.*)?"
semanage fcontext -a -t lib_t "/usr(/local/nixfs/upper)?/nix/store/[^/]+/lib(/.*)?"
semanage fcontext -a -t systemd_unit_file_t "/usr(/local/nixfs/upper)?/nix/store/[^/]+/lib/systemd/system(/.*)?"
semanage fcontext -a -t man_t "/usr(/local/nixfs/upper)?/nix/store/[^/]+/man(/.*)?"
semanage fcontext -a -t bin_t "/usr(/local/nixfs/upper)?/nix/store/[^/]+/s?bin(/.*)?"
semanage fcontext -a -t usr_t "/usr(/local/nixfs/upper)?/nix/store/[^/]+/share(/.*)?"
semanage fcontext -a -t var_run_t "/usr(/local/nixfs/upper)?/nix/var/nix/daemon-socket(/.*)?"
semanage fcontext -a -t usr_t "/usr(/local/nixfs/upper)?/nix/var/nix/profiles(/per-user/[^/]+)?/[^/]+"
