#!/bin/bash

clear

update_dimensions() {
    term_width=$(tput cols)
    term_height=$(tput lines)
    bar_width=$((term_width * 70 / 100))
    [[ $bar_width -gt $term_width ]] && bar_width=$term_width

    msg1=$1
    msg2=$2
    msg1_row=$((term_height / 2 - 1))
    msg2_row=$((term_height / 2))
    msg1_col=$(( (term_width - ${#msg1}) / 2 ))
    msg2_col=$(( (term_width - ${#msg2}) / 2 ))

    clear
    tput cup $msg1_row $msg1_col
    printf "%s" "$msg1"
    tput cup $msg2_row $msg2_col
    printf "%s" "$msg2"
}

tput civis
trap "tput cnorm; clear; exit" EXIT
update_dimensions "$1" "$2"
trap 'update_dimensions "$1" "$2"' SIGWINCH

offset=0
frame=0
frames_per_cycle=200

if [[ -z "$3" ]]; then
    echo "Error: No command provided to run in the background."
    tput cnorm
    exit 1
fi

$3 &
cmd_pid=$!

while kill -0 $cmd_pid 2>/dev/null; do
    tput cup 0 0
    tput el

    for ((i = 0; i < term_width; i++)); do
        index=$(( (i - offset + term_width) % term_width ))
        if (( index < bar_width )); then
            printf "="
        else
            printf "#"
        fi
    done

    angle=$(( (frame * 360 / frames_per_cycle) % 360 ))
    rad=$(echo "$angle * 3.14159 / 180" | bc -l)
    delay=$(echo "0.001 + (0.004 * (1 + s($rad)))" | bc -l)

    sleep $delay

    ((offset = (offset + 1) % term_width))
    ((frame = (frame + 1) % frames_per_cycle))
done

tput cnorm
clear