#!/bin/bash

clear_box=yes
clear

loading_message="Loading, please wait..."
command_to_run=""

for arg in "$@"; do
	if [[ "$arg" == --msg=* ]]; then
		loading_message="${arg#--msg=}"
	elif [[ "$arg" == --cmd=* ]]; then
		command_to_run="${arg#--cmd=}"
	fi
done

trap cleanup SIGINT SIGTERM SIGHUP SIGQUIT

get_terminal_dimensions() {
	height=$(tput lines)
	width=$(tput cols)
	echo "$height $width"
}

draw_box() {
	local term_height="$1"
	local term_width="$2"
	local box_width=$((term_width * 3 / 4))
	local box_height=3
	local box_start_y=$(( (term_height - box_height) / 2 ))
	local box_start_x=$(( (term_width - box_width) / 2 ))

	tput cup "$box_start_y" "$box_start_x"

	for ((i = 0; i < box_width; i++)); do
		printf "#"
	done
	echo

	tput cup "$((box_start_y + 1))" "$box_start_x"
	printf "#"
	tput cuf "$((box_width - 2))"
	printf "#"
	echo

	tput cup "$((box_start_y + 2))" "$box_start_x"
	for ((i = 0; i < box_width; i++)); do
		printf "#"
	done
	echo
}

display_message() {
	local term_height="$1"
	local term_width="$2"
	local box_width=$((term_width * 3 / 4))
	local box_start_y=$(( (term_height - 3) / 2 ))
	local box_start_x=$(( (term_width - box_width) / 2 ))
	local message_y=$((box_start_y - 2))
	local message_x=$(( (term_width - ${#loading_message}) / 2 ))

	tput cup "$message_y" "$message_x"
	printf "%s" "$loading_message"
}

clear_box_interior() {
	local term_height="$1"
	local term_width="$2"
	local box_width=$((term_width * 3 / 4))
	local box_height=3
	local box_start_y=$(( (term_height - box_height) / 2 ))
	local box_start_x=$(( (term_width - box_width) / 2 ))

	tput cup "$((box_start_y + 1))" "$((box_start_x + 1))"

	for ((i = 0; i < $((box_width - 2)); i++)); do
		printf " "
	done
}

draw_bar() {
	local term_width="$1"
	local box_width=$((term_width * 3 / 4))
	local box_start_x=$(( (term_width - box_width) / 2 ))
	local bar_width=$((term_width / 5))
	local bar_y=$((box_start_y + 1))
	local max_bar_offset=$((box_width - bar_width - 2))

	tput cup "$bar_y" "$((box_start_x + 1 + old_bar_position))"
	for ((i = 0; i < old_bar_width; i++)); do
		printf " "
	done

	tput cup "$bar_y" "$((box_start_x + 1 + bar_position))"
	for ((i = 0; i < bar_width; i++)); do
		printf "-"
	done

	old_bar_position="$bar_position"
	old_bar_width="$bar_width"
}

hide_cursor() {
	tput civis
}

show_cursor() {
	tput cnorm
}

cleanup() {
	clear
	show_cursor
	exit 0
}

run_command() {
	if [[ -n "$command_to_run" ]]; then
		eval "$command_to_run" &
		command_pid=$!
		wait "$command_pid"
		command_exit_code=$?
		if [[ $command_exit_code -eq 0 ]]; then
			kill -9 $$
			cleanup
		elif [[ $command_exit_code -ne 0 ]]; then
			cleanup
			echo "Error: Command failed with exit code $command_exit_code"
			exit $command_exit_code
		fi
	fi
}

old_term_dimensions=""
bar_position=0
old_bar_position=0
direction=1
animation_speed=0.02

hide_cursor

initial_dimensions=$(get_terminal_dimensions)
term_height=$(echo "$initial_dimensions" | awk '{print $1}')
term_width=$(echo "$initial_dimensions" | awk '{print $2}')
box_start_y=$(( (term_height - 3) / 2 ))

draw_box "$term_height" "$term_width"
display_message "$term_height" "$term_width"

old_term_dimensions="$initial_dimensions"

run_command &

while true; do
	current_dimensions=$(get_terminal_dimensions)

	if [[ "$current_dimensions" != "$old_term_dimensions" ]]; then
		clear
		term_height=$(echo "$current_dimensions" | awk '{print $1}')
		term_width=$(echo "$current_dimensions" | awk '{print $2}')
		box_start_y=$(( (term_height - 3) / 2 ))
		draw_box "$term_height" "$term_width"
		display_message "$term_height" "$term_width"
		old_term_dimensions="$current_dimensions"
	fi

	term_width=$(echo "$current_dimensions" | awk '{print $2}')
	box_width=$((term_width * 3 / 4))
	max_bar_offset=$((box_width - $((term_width / 5)) - 2))

	draw_bar "$term_width"

	if [[ "$clear_box" == "yes" ]]; then
		clear_box_interior "$term_height" "$term_width"
		unset clear_box
	fi

	bar_position=$((bar_position + direction))

	if [[ "$bar_position" -le 0 ]]; then
		direction=1
	elif [[ "$bar_position" -ge "$max_bar_offset" ]]; then
		direction=-1
	fi

	sleep $animation_speed
done