#!/bin/bash

status() {
    local TRANSIT_STATUS="NOT_MOUNTED"
    if [[ $* == *--no-truncate* ]]; then
        local sys_cmdline=$(cat /proc/cmdline | sed -E 's/(ostree=)[^ ]+/\1.../' | sed -E 's/(BOOT_IMAGE=)[^ ]+/\1.../' | sed -E 's/(uuid=)[^ ]+/\1.../' | sed -E 's/(luks_uuid=)[^ ]+/\1.../')
    else
        local sys_cmdline=$(caat /proc/cmdline)
    fi
    [[ -f /etc/transit/transit-status ]] && TRANSIT_STATUS=$(cat /etc/transit/transit-status)
    cat <<EOF
bourbonOS $(cat /etc/bourbonOS_version)
Pesticide: $(/usr/libexec/pesticide/status) | $(/usr/libexec/pesticide/version)
Transit: "$TRANSIT_STATUS" | $(cat /etc/transit_version)
=======================
host: $(hostname)
kargs: "$sys_cmdline"
kernver: $(uname -r)
=======================
ostree status:
$(ostree admin status)
EOF
}

help() {
    cat <<EOF
Usage: cherry baseos [option]

Options:
    exec                          run a command on the host system
    upgrade                       upgrade the host system and related utilities
    status [--no-truncate]        show the status of the host system
    help                          show this dialogue
EOF
}

case "$1" in
    exec) shift; $@ ;;
    upgrade) clear; echo "Please authorize to start your system upgrade."; pkexec /usr/libexec/ostools/update --interactive ;;
    status) shift; status $@ ;;
    help | *) help ;;
esac