#!/bin/bash

readonly FILENAME_TMP=$(mktemp)

help() {
    cat <<EOF
Usage: cherry containeros [option]

Options:
    create                        create a new container
    rm <container_name>           remove an existing container
    save <container_name>         save the specified container to an image
    load <image_path>             load a container from an image
    switch <container_name>       switch to a different container
    list                          list all containers
    help                          show this dialogue
EOF
}

throbber() {
    /usr/libexec/ostools/throbber $@
}

case "$1" in
    create)
        echo "Do you want to:"
        select container in "Choose from a list of images" "Specify your own (advanced)"; do
            case "$container" in
                "Choose from a list of images")
                    echo "Select a container image from the list:"
                    select image $(cat /etc/containerconf/.cherry/list.txt); do
                        [[ -n $image ]] && throbber --msg="Creating container $image..." --cmd="distrobox-assemble create --file /etc/containerconf/$image.ini" && echo "Done! You can switch to the container using 'cherry container switch'." && exit 0
                    done
                    ;;
                "Specify your own (advanced)")
                    read -p "Container URL/alias: " manual_container_url
                    read -p "Container name: " manual_container_name
                    cp /etc/containerconf/.ini-template "/tmp/$FILENAME_TMP.ini"
                    sed -i "s/<name>/$manual_container_name/g" "/tmp/$FILENAME_TMP.ini"
                    sed -i "s/<url>/$manual_container_url/g" "/tmp/$FILENAME_TMP.ini"
                    nano "/tmp/$FILENAME_TMP.ini"
                    throbber --msg="Creating container.." --cmd="distrobox-assemble create --file /tmp/$FILENAME_TMP.ini"
                    rm "/tmp/$FILENAME_TMP.ini"
                    echo "Done! You can switch to the container using 'cherry branch jump'."
                    exit 0
                    ;;
            esac
        done
        ;;
    rm)
        containers=$(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$')
        [[ -z $containers ]] && echo "No containers to remove." && exit 1
        echo "Select a container by its number to remove it."
        select container in $containers; do
            [[ -n $container ]] && throbber --msg="Removing container..." --cmd="distrobox-rm $container" && echo "Removed $container." && exit 0
        done
        ;;
    save)
        containers=$(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$')
        [[ -z $containers ]] && echo "No containers to save." && exit 1
        echo "Select a container by its number to save it to an image."
        select container in $containers; do
            [[ -n $container ]] && throbber --msg="Saving container..." --cmd="podman save $container $HOME/$container.tar" && echo "Container image saved at $HOME/$container.tar" && exit 0
        done
        ;;
    load)
        [[ ! -f "$2" ]] && echo "Error: Image path not found." && exit 1
        throbber --msg="Loading container image..." --cmd="podman load $2"
        echo "Container loaded from $2. You can switch to it using 'cherry container switch'."
        ;;
    switch)
        containers=$(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$')
        [[ -z $containers ]] && echo "No containers to switch to." && exit 1
        echo "Select a container by its number to switch to it."
        select container in $containers; do
            [[ -n $container ]] && echo "Switching to $container..." && distrobox-enter "$container"
        done
        ;;
    list) 
        distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$' 
        ;;
    help | *) 
        help 
        ;;
esac