#!/bin/bash

set -oue pipefail

wait_for_directory() {
    local directory="$1"
    local timeout="${2:-300}"
    local interval=1
    local counter=0

    echo "Waiting for home directory to be mounted (timeout: ${timeout} seconds)..."

    while [[ ! -d "$HOME" ]]; do
        if [[ "$counter" -ge "$timeout" ]]; then
            echo "Error: Timeout reached. Home directory still not mounted."
            echo "Something has went extremely wrong."
            return 1
        fi
        sleep "$interval"
        counter=$((counter + interval))
    done

    echo "Home directory mounted. Continuing..."
    return 0
}

if wait_for_directory "$HOME"; then
    source "$HOME"/.bkconf/bk.conf
    if [[ ! -d /var/usrlocal/transit/backup/"$USER"-backup ]]; then
        openssl rand -base64 256 > "$HOME"/.bkconf/pass.key
        restic init --repo /var/usrlocal/transit/backup/"$USER"-backup --password-file "$HOME"/.bkconf/pass.key
        restic backup --repo /var/usrlocal/transit/backup/"$USER"-backup "$exclude" "$HOME" --password-file "$HOME"/.bkconf/pass.key
    elif [[ -d /var/usrlocal/transit/backup/"$USER"-backup ]]; then
        restic backup --repo /var/usrlocal/transit/backup/"$USER"-backup "$exclude" "$HOME" --password-file "$HOME"/.bkconf/pass.key
    fi
else
    exit 1
fi