#!/bin/bash

set -oue pipefail

if [[ -t 0 || -z "$(cat -)" ]]; then
    echo "Error: No input received." >&2
    exit 0
elif [[ "$(id -u "$1" 2>/dev/null)" -lt 1000 ]] || ! grep -q "^$1:" /etc/passwd; then
    exit 0
fi

echo "Starting setup."
pass=$(cat)
set_readme="false"
transit_dir="/var/usrlocal/transit"

if [[ -d /var/home/"$1"/Desktop ]]; then
    echo "Initialized homedir detected."
    set_readme="true"
fi

echo "Creating image..."
truncate -s $(df -h /var | tail -n 1 | awk '{print $2}') "$transit_dir"/repo/"$1".homedir

echo "Associating image..."
LOOPDEV=$(losetup -f --show "$transit_dir"/repo/"$1".homedir)
[[ -z "$LOOPDEV" ]] && echo "Error: No loop device found for "$transit_dir"/repo/$1.homedir." && exit 1

echo "Encrypting image..."
echo "$pass" | cryptsetup --type luks2 --cipher aes-xts-plain64 luksFormat /dev/loop0
echo "$pass" | cryptsetup luksOpen $LOOPDEV init_transit-"$(cat /etc/transit/transit-id)"
unset pass

echo "Formatting image..."
mkfs.ext4 -F /dev/mapper/init_transit-"$(cat /etc/transit/transit-id)"

echo "Mounting and preparing image..."
mount /dev/mapper/init_transit-"$(cat /etc/transit/transit-id)" /var/home
mkhomedir_helper "$1"
[[ "$set_readme" == "true" ]] && cp /etc/transit/.README.md /var/home/"$1"/README.md

echo "Initializing backup repository..."
mkdir -pm 700 "$transit_dir"/backup/"$1"-backup
chown "$1":"$1" "$transit_dir"/backup/"$1"-backup
/usr/libexec/transit/maintenance &

echo "Unmounting image..."
umount /var/home

echo "Cleaning up..."
cryptsetup luksClose init_transit-"$(cat /etc/transit/transit-id)"
losetup -d "$LOOPDEV"

echo "Setup finished."