#!/bin/bash

set -oue pipefail

echo "Starting setup."
pass=$(cat)
set_readme="false"

if [[ -d /var/home/"$1"/Desktop ]]; then
    echo "Initialized homedir detected."
    set_readme="true"
fi

echo "Associating device..."
LOOPDEV=$(losetup -f --show /var/usrlocal/transit/repo/"$1".homedir)

if [[ -z "$LOOPDEV" ]]; then
    echo "Error: No loop device found for /var/usrlocal/transit/repo/$1.homedir."
    exit 1
fi

echo "Creating image..."
truncate -s $(df -h /var/ | tail -n 1 | awk '{print $2}') /var/usrlocal/transit/repo/"$1".homedir
losetup "$LOOPDEV" /var/usrlocal/transit/repo/"$1".homedir

echo "Encrypting image..."
echo "$pass" | cryptsetup --type luks2 --cipher aes-xts-plain64 luksFormat /dev/loop0
echo "$pass" | cryptsetup luksOpen $LOOPDEV init_transit-"$(cat /etc/transit/transit-id)"
unset pass

echo "Formatting image..."
mkfs.ext4 -F /dev/mapper/init_transit-"$(cat /etc/transit/transit-id)"

echo "Mounting and preparing..."
mount /dev/mapper/init_transit-"$(cat /etc/transit/transit-id)" /var/home
mkhomedir_helper "$1"
[[ "$set_readme" == "true" ]] && cp /etc/transit/.README.md /var/home/"$1"/README.md

echo "Unmounting..."
umount /var/home

echo "Cleaning up..."
cryptsetup luksClose init_transit-"$(cat /etc/transit/transit-id)"
losetup -d "$LOOPDEV"

echo "Setup finished."