#!/bin/bash

set -oue pipefail

if [[ -t 0 || -z "$(cat -)" ]]; then
    echo "Error: No input received." >&2
    exit 1
fi

pass=$(cat)

if [[ "$(id -u "$1")" -lt 1000 ]]; then
    exit 0
elif [[ ! -f /var/usrlocal/transit/repo/"$1".homedir ]]; then
    echo "$pass" | /usr/libexec/transit/setup-transit "$1"
fi

echo "Associating image..."
LOOPDEV=$(losetup -f --show /var/usrlocal/transit/repo/"$1".homedir)

if [[ -z "$LOOPDEV" ]]; then
    echo "Error: No loop device found for /var/usrlocal/transit/repo/$1.homedir."
    exit 1
fi

echo "Decrypting image..."
echo "$pass" | cryptsetup luksOpen "$LOOPDEV" in_transit-$(cat /etc/transit/transit-id)

unset pass

echo "Mounting image..."
mount --bind -o ro /var/home /var/usrlocal/transit/varhome
mount /dev/mapper/in_transit-$(cat /etc/transit/transit-id) /var/home

echo "Mounted image successfully."
echo "MOUNTED" > /etc/transit/transit-status