#!/bin/bash

set -oue pipefail

losetup -f /var/usrlocal/transit/repo/$1.homedir /dev/loop0
cat /dev/stdin | cryptsetup luksOpen /dev/loop0 in_transit-$(cat /etc/transit-id)

mount /dev/mapper/in_transit-$(cat /etc/transit-id) /var/usrlocal/transit/main/homelayer
mount -t overlay overlay -o lowerdir=/var/home/$1,upperdir=/var/usrlocal/transit/main/homelayer,workdir=/var/usrlocal/transit/main/.work /var/home/$1

echo "Mounted at /home/$1" > /etc/transit_status