#!/bin/bash

set -oue pipefail
shopt -s extglob

if [[ "$(id -u "$1")" -lt 1000 || "$1" == "root" || ! -f /var/usrlocal/transit/repo/"$1".homedir ]]; then
    exit 0
fi

LOOPDEV=$(losetup | grep /var/usrlocal/transit/repo/"$1".homedir | cut -d':' -f1)

if [[ -z "$LOOPDEV" ]]; then
    echo "Error: No loop device found for /var/usrlocal/transit/repo/$1.homedir."
    exit 1
fi

echo "Unmounting..."
umount /var/home
umount /var/usrlocal/transit/varhome
cryptsetup luksClose in_transit-$(cat /etc/transit/transit-id)
losetup -d "$LOOPDEV"

echo "Cleaning up..."
rm /etc/transit/transit-status

echo "Unmounted /var/home/$1."