#!/bin/bash

set -oue pipefail
shopt -s extglob

transit_dir="/var/usrlocal/transit"

if [[ "$(id -u "$1")" -lt 1000 || ! -f "$transit_dir"/repo/"$1".homedir ]]; then
    exit 0
fi

LOOPDEV=$(losetup | grep "$transit_dir"/repo/"$1".homedir | cut -d':' -f1)

if [[ -z "$LOOPDEV" ]]; then
    echo "Error: No loop device found for "$transit_dir"/repo/$1.homedir."
    exit 1
fi

echo "Unmounting image..."
umount /var/home
umount "$transit_dir"/varhome
cryptsetup luksClose in_transit-$(cat /etc/transit/transit-id)
losetup -d "$LOOPDEV"

echo "Cleaning up..."
rm /etc/transit/transit-status

echo "Unmounted image successfully."