#!/bin/bash

if [[ "$1" != "mount" ]]; then
    set -euo pipefail

    if [[ -d /var/usrlocal/homefs ]]; then
        echo "Exiting"
        exit 0
    fi

    mkdir -p /var/usrlocal/homefs
    openssl -hex 12 > /var/usrlocal/homefs/.homefs-salt
    chmod 700 /var/usrlocal/homefs/.homefs-salt

    MAX_SIZE=$(df -h /var/home | awk 'NR==2 {print $2}')
    SALT=$(cat /var/usrlocal/homefs/.homefs-salt)
    KEY_DESC="homefs-mountkey-$SALT"
    BOARD_VENDOR=$(cat /sys/class/dmi/id/board_vendor 2>/dev/null || echo "no-vendor")
    PRODUCT_SKU=$(cat /sys/class/dmi/id/product_sku 2>/dev/null || echo "no-sku")
    HWID_RAW="${BOARD_VENDOR}${PRODUCT_SKU}"
    KEY_MATERIAL=$(echo -n "${SALT}${HWID_RAW}" | sha256sum | cut -d' ' -f1)

    keyctl add user "$KEY_DESC" "$KEY_MATERIAL" @u
    IMG_PATH="/var/usrlocal/homefs/homefs.img"
    truncate -s "$MAX_SIZE" "$IMG_PATH"
    LOOPDEV=$(losetup -f)
    echo -n "$KEY_MATERIAL" | losetup -e AES256 -p 0 "$LOOPDEV" "$IMG_PATH"
    mkfs.ext4 -F "$LOOPDEV"
    mount "$LOOPDEV" /tmp/homefs
    mv /var/home/* /tmp/homefs/
    umount /tmp/homefs
    losetup -d "$LOOPDEV"

    systemctl restart mount-homefs.service

    for USER_DIR in /var/home/*;
    do
        if [ -d "$USER_DIR" ]; then
            USERNAME=$(basename "$USER_DIR")
            chown "$USERNAME:$USERNAME" "$USER_DIR"
            chmod 700 $USER_DIR
            restorecon -Rv $USER_DIR
        fi
    done

    touch /etc/.homefs.setup-is-done
else
    set -euo pipefail
    SALT=$(cat /var/usrlocal/homefs/.homefs-salt)
    KEY_DESC="homefs-mount-$SALT"
    BOARD_VENDOR=$(cat /sys/class/dmi/id/board_vendor 2>/dev/null || echo "no-vendor")
    PRODUCT_SKU=$(cat /sys/class/dmi/id/product_sku 2>/dev/null || echo "no-sku")
    HWID_RAW="${BOARD_VENDOR}${PRODUCT_SKU}"

    KEY_MATERIAL=$(echo -n "${SALT}${HWID_RAW}" | sha256sum | cut -d' ' -f1)
    keyctl add user "$KEY_DESC" "$KEY_MATERIAL" @u

    IMG_PATH="/var/usrlocal/homefs/homefs.img"
    LOOPDEV=$(losetup -f)
    echo -n "$KEY_MATERIAL" | losetup -e AES256 -p 0 "$LOOPDEV" "$IMG_PATH"
    mount "$LOOPDEV" /var/home
fi