#!/bin/bash

if [[ "$(id -u)" -eq 0 ]]; then
    echo "Initializing..."
else
    echo "Failed."
fi

HOMEFS_DIR="/var/usrlocal/homefs"
HOMEFS_IMG="$HOMEFS_DIR/homefs.img"
HOME_DIR="/var/home"
MOUNT_POINT="/tmp/homefs"
SALT_FILE="$HOMEFS_DIR/.homefs-salt"
KEY_DESC="homefs-mount-$(cat $SALT_FILE)"
KEY_MATERIAL=$(echo -n "$(cat $SALT_FILE)$(cat /sys/class/dmi/id/product_sku 2>/dev/null || echo "no-sku")$(cat /sys/class/dmi/id/board_vendor 2>/dev/null || echo "no-vendor")" | sha256sum | cut -d' ' -f1)
LOOP_DEVICE=$(losetup -f)

if [[ "$1" == "--mount-all" ]]; then
    set -oue pipefail

    echo "Mounting homefs+nixfs..."

    keyctl add user "$KEY_DESC" "$KEY_MATERIAL" @u

    echo -n "$KEY_MATERIAL" | losetup -e AES256 -p 0 "$LOOP_DEVICE" "$HOMEFS_IMG"
    mount "$LOOP_DEVICE" "$HOME_DIR"
    mount -t overlay overlay -o "lowerdir=/nix,upperdir=/var/usrlocal/nixfs/upper,workdir=/var/usrlocal/nixfs/work" /nix

    restorecon -RFv /{usr/local/nixfs/,var/home/}

    echo "homefs+nixfs mounted successfully."
else
    set -oue pipefail

    echo "Setting up encrypted homefs..."
    if [[ -d "$HOMEFS_DIR" ]]; then
        echo "$HOMEFS_DIR already exists. Exiting setup."
        exit 0
    fi

    mkdir -p "$HOMEFS_DIR"
    openssl rand -hex 12 > "$SALT_FILE"
    chmod 700 "$SALT_FILE"

    keyctl add user "$KEY_DESC" "$KEY_MATERIAL" @u

    mkdir $HOMEFS_DIR
    truncate -s "$(df -h "$HOME_DIR" | awk 'NR==2 {print $2}')" "$HOMEFS_IMG"
    echo -n "$KEY_MATERIAL" | losetup -e AES256 -p 0 "$LOOP_DEVICE" "$HOMEFS_IMG"
    mkfs.ext4 -F "$LOOP_DEVICE"
    mount "$LOOP_DEVICE" "$MOUNT_POINT"
    mv "$HOME_DIR"/* "$MOUNT_POINT"/
    umount "$MOUNT_POINT"
    losetup -d "$LOOP_DEVICE"

    echo "Setting up nixfs..."
    mkdir -p /var/usrlocal/nixfs/{upper,work}

    semanage fcontext -a -t etc_t "/nix/store/[^/]+/etc(/.*)?"
    semanage fcontext -a -t lib_t "/nix/store/[^/]+/lib(/.*)?"
    semanage fcontext -a -t systemd_unit_file_t "/nix/store/[^/]+/lib/systemd/system(/.*)?"
    semanage fcontext -a -t man_t "/nix/store/[^/]+/man(/.*)?"
    semanage fcontext -a -t bin_t "/nix/store/[^/]+/s?bin(/.*)?"
    semanage fcontext -a -t usr_t "/nix/store/[^/]+/share(/.*)?"
    semanage fcontext -a -t var_run_t "/nix/var/nix/daemon-socket(/.*)?"
    semanage fcontext -a -t usr_t "/nix/var/nix/profiles(/per-user/[^/]+)?/[^/]+"
    semanage fcontext -a -t etc_t "/usr/local/nixfs/upper/nix/store/[^/]+/etc(/.*)?"
    semanage fcontext -a -t lib_t "/usr/local/nixfs/upper/store/[^/]+/lib(/.*)?"
    semanage fcontext -a -t systemd_unit_file_t "/usr/local/nixfs/upper/store/[^/]+/lib/systemd/system(/.*)?"
    semanage fcontext -a -t man_t "/usr/local/nixfs/upper/store/[^/]+/man(/.*)?"
    semanage fcontext -a -t bin_t "/usr/local/nixfs/upper/store/[^/]+/s?bin(/.*)?"
    semanage fcontext -a -t usr_t "/usr/local/nixfs/upper/store/[^/]+/share(/.*)?"
    semanage fcontext -a -t var_run_t "/usr/local/nixfs/upper/var/nix/daemon-socket(/.*)?"
    semanage fcontext -a -t usr_t "/usr/local/nixfs/upper/var/nix/profiles(/per-user/[^/]+)?/[^/]+"

    echo "Mounting all..."
    systemctl restart mount-loopfs.service gdm.service nix-daemon.socket
    
fi