#!/bin/bash

if [ "${0}" = "${BASH_SOURCE[0]}" ]; then
    echo "Internal error."
    exit
fi

stem-help() {
    cat <<EOF
Usage: cherry baseos [option]

Options:
  exec                          run a command on the host system
  upgrade                       upgrade the host system and related utils
  status                        show the status of the host system
  help                          show this dialogue
EOF
}

branch-help() {
    cat <<EOF
Usage: cherry containeros [option]

Options:
  new                           create a new container
  rm <container_name>           remove an existing container
  save <container_name>         save the specified container to an image
  load <image_path>             load a container from an image
  switch <container_name>       switch to a different container
  list                          list all containers
  help                          show this dialogue
EOF
}

pesticide-help() {
    cat <<EOF
Usage: cherry fsguard [option]

Options:
  status                      show the status of enrolled directories
  check                       check the integrity of enrolled directories
  apply                       enroll a new directory
  help                        show this dialogue
EOF
}