#!/bin/bash

if [ "${0}" = "${BASH_SOURCE[0]}" ]; then
    echo "Internal error."
    exit
fi

status() {
    local TRANSIT_STATUS="NOT_MOUNTED"
    [[ -f /etc/transit/transit-status ]] && TRANSIT_STATUS=$(cat /etc/transit/transit-status)
    cat <<EOF
bourbonOS $(cat /etc/bourbonOS_version)
Pesticide: $(/usr/libexec/pesticide/status) | $(/usr/libexec/pesticide/version)
Transit: $TRANSIT_STATUS | $(cat /etc/transit_version)
=======================
host: $(hostname)
kargs: $(cat /proc/cmdline | sed -E 's/(ostree=)[^ ]+/\1.../' | sed -E 's/(BOOT_IMAGE=)[^ ]+/\1.../' | sed -E 's/(uuid=)[^ ]+/\1.../' | sed -E 's/(luks_uuid=)[^ ]+/\1.../')
kernver: $(uname -r)
=======================
ostree status:
$(ostree admin status)
EOF
}

version() {
    echo "cherry version 3.1.5"
}

throbber() {
    /usr/libexec/ostools/throbber $@
}

baseos() {
    case "$1" in
        exec) shift; $@ ;;
        upgrade) clear; echo "Please authorize to start your system upgrade."; pkexec /usr/libexec/ostools/update --interactive ;;
        status) status ;;
        help | *) stem-help ;;
    esac
}

container() {
    case "$1" in
        new)
            echo "Do you want to:"
            select container in "Choose from a list of images" "Specify your own (advanced)"; do
                case "$container" in
                    "Choose from a list of images")
                        echo "Select an image from the list:"
                        select image $(cat $CONTAINER_LIST_FILE); do
                            [[ -n $image ]] && throbber --msg="Creating container..." --cmd="distrobox-assemble create --file /etc/containerconf/$image.ini" && echo "Done! You can switch to the container using 'cherry branch jump'." && exit 0
                        done
                        ;;
                    "Specify your own (advanced)")
                        read -p "Container URL/alias: " manual_container_url
                        read -p "Container name: " manual_container_name
                        cp /etc/containerconf/.ini-template "/tmp/$FILENAME_TMP.ini"
                        sed -i "s/<name>/$manual_container_name/g" "/tmp/$FILENAME_TMP.ini"
                        sed -i "s/<url>/$manual_container_url/g" "/tmp/$FILENAME_TMP.ini"
                        nano "/tmp/$FILENAME_TMP.ini"
                        throbber --msg="Creating container.." --cmd="distrobox-assemble create --file /tmp/$FILENAME_TMP.ini"
                        rm "/tmp/$FILENAME_TMP.ini"
                        echo "Done! You can switch to the container using 'cherry branch jump'."
                        exit 0
                        ;;
                esac
            done
            ;;
        rm)
            containers=$(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$')
            [[ -z $containers ]] && echo "No containers to remove." && exit 1
            echo "Select a container by its number to remove it."
            select container in $containers; do
                [[ -n $container ]] && throbber --msg="Removing container..." --cmd="distrobox-rm $container" && echo "Removed $container." && exit 0
            done
            ;;
        save)
            containers=$(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$')
            [[ -z $containers ]] && echo "No containers to save." && exit 1
            echo "Select a container by its number to save it to an image."
            select container in $containers; do
                [[ -n $container ]] && throbber --msg="Saving container..." --cmd="podman save $container $HOME/$container.tar" && echo "Container image saved at $HOME/$container.tar" && exit 0
            done
            ;;
        load)
            [[ ! -f "$2" ]] && echo "Error: Image path not found." && exit 1
            throbber --msg="Loading container image..." --cmd="podman load $2"
            echo "Container loaded from $2. You can switch to it using 'cherry branch jump'."
            ;;
        switch)
            containers=$(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$')
            [[ -z $containers ]] && echo "No containers to switch to." && exit 1
            echo "Select a container by its number to switch to it."
            select container in $containers; do
                [[ -n $container ]] && export CONTAINER="$container"
            done
            echo "Switched to container "$CONTAINER"."
            ;;
        list) distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$' ;;
        help | *) branch-help ;;
    esac
}

transit() {
    local rflags="-r /var/home/backups --password-file $HOME/.bkconf/pass.key"
    case "$1" in
        status) cat /etc/transit/transit-status ;;
        bkup) restic $rflags backup "$HOME" $exclude;;
        bkls)
            if [[ -z $2 ]]; then
                echo "No snapshot specified."
                echo "Search for a snapshot to use with 'transit bklist'."
            else
                restic $rflags ls "$2"
            fi
            ;;
        bkconf)
            nano "$HOME"/.bkconf/bk.conf
            echo "Changes applied."
            ;;
        bkdiff)
            if [[ -z $2 || -z $3 ]]; then
                echo "Insufficient arguments provided."
                echo "Search for snapshots to diff with 'transit bklist'."
            else
                restic $rflags diff "$2" "$3"
            fi
            ;;
        bkstat) restic $rflags stats --human-readable;;
        bklist) restic $rflags snapshots ;;
        bkrestore)
            if [[ -z $2 ]]; then
                echo "No snapshot specified."
                echo "Search for a snapshot to restore with 'transit bklist'."
            else
                restic $rflags restore $2 --target "$HOME"
            fi
            ;;
        bkcheck) restic $rflags check;;
    esac
}