#!/bin/bash

USER_NAME=$(whoami)
HOST_NAME=$(hostname)
FULL_PATH=$(pwd)
GREEN="\033[0;32m"
BLUE="\033[0;34m"
RESET="\033[0m"

truncate_path() {
    local path="$1"
    local home="$HOME"
    
    if [[ "$path" == "$home"* ]]; then
        path="~${path#$home}"
    fi
    
    local dirs=(${path//\// })
    local dir_count=${#dirs[@]}
    
    if [[ $dir_count -gt 2 ]]; then
        local last_two="${dirs[$((dir_count-2))]}/${dirs[$((dir_count-1))]}"
        
        if [[ -z "${dirs[$((dir_count-1))]}" ]]; then
            last_two="${dirs[$((dir_count-3))]}/${dirs[$((dir_count-2))]}"
        fi
        
        if [[ "$path" == "~"* ]]; then
            echo ".../$(basename "$(dirname "$last_two")")/$(basename "$last_two")"
        else
            echo ".../$(basename "$(dirname "$last_two")")/$(basename "$last_two")"
        fi
    else
        echo "$path"
    fi
}

WORK_DIR=$(truncate_path "$FULL_PATH")

if "$HOST"; then
    printf "[${USER_NAME}@${CONTAINER}]-[${WORK_DIR}]$ "
elif ! "$HOST"; then
    printf "${GREEN}[${BLUE}${USER_NAME}@${HOST_NAME}${GREEN}]-[${BLUE}${WORK_DIR}${GREEN}]${RESET}$ "
else
    printf "$> "
fi