#!/bin/bash

readonly rflags="-r /var/home/backups --password-file $HOME/.bkconf/pass.key"

source "$HOME"/.bkconf/bk.conf

transit-help() {
    cat <<EOF
Usage: transit [option]

Options:
    status                      show the status of Transit
    bkup                        run a homedir backup
    bkls <snapshot-id>          ls a specified snapshot
    bkconf                      modify backup configuration
    bkdiff <id> <id2>           diff two specified snapshots
    bkstat                      repository statistics
    bklist                      list all snapshots
    bkrestore <snapshot-id>     restore a snapshot
    bkcheck                     verify repository integrity

EOF
}

case "$1" in
    status)
        cat /etc/transit/transit-status
        ;;
    bkup)
        restic $rflags backup "$HOME" $exclude
        ;;
    bkls)
        if [[ -z $2 ]]; then
            echo "No snapshot specified."
            echo "Search for a snapshot to use with 'transit bklist'."
        else
            restic $rflags ls "$2"
        fi
        ;;
    bkconf)
        nano "$HOME"/.bkconf/bk.conf
        echo "Changes applied."
        ;;
    bkdiff)
        if [[ -z $2 || -z $3 ]]; then
            echo "Insufficient arguments provided."
            echo "Search for snapshots to diff with 'transit bklist'."
        else
            restic $rflags diff "$2" "$3"
        fi
        ;;
    bkstat)
        restic $rflags stats --human-readable
        ;;
    bklist)
        restic $rflags snapshots
        ;;
    bkrestore)
        if [[ -z $2 ]]; then
            echo "No snapshot specified."
            echo "Search for a snapshot to restore with 'transit bklist'."
        else
            restic $rflags restore $2 --target "$HOME"
        fi
        ;;
    bkcheck)
        restic $rflags check
        ;;
    help | *)
        transit-help
        ;;
esac