#!/bin/bash

clear

update_dimensions() {
    term_width=$(tput cols)
    term_height=$(tput lines)
    bar_width=$((term_width * 70 / 100))
    [[ $bar_width -gt $term_width ]] && bar_width=$term_width
    bar=$(printf "%-${bar_width}s" "" | tr ' ' '=')

    msg1="Hi! We're just finishing things up in the background."
    msg2="This may take a second or two."
    msg1_row=$((term_height / 2 - 1))
    msg2_row=$((term_height / 2))
    msg1_col=$(( (term_width - ${#msg1}) / 2 ))
    msg2_col=$(( (term_width - ${#msg2}) / 2 ))
}

tput civis
trap "tput cnorm; clear; exit" EXIT
update_dimensions
trap update_dimensions SIGWINCH

offset=0
frame=0
frames_per_cycle=300  # Long sine wave cycle

while true; do
    # Always draw on top row
    tput cup 0 0
    tput el

    for ((i=0; i<term_width; i++)); do
        index=$(( (i - offset + bar_width) % term_width ))
        if (( index < bar_width )); then
            printf "="
        else
            printf "#"
        fi
    done

    tput cup $msg1_row $msg1_col
    printf "%s" "$msg1"
    tput cup $msg2_row $msg2_col
    printf "%s" "$msg2"

    angle=$(( (frame * 360 / frames_per_cycle) % 360 ))
    rad=$(echo "$angle * 3.14159 / 180" | bc -l)
    delay=$(echo "0.001 + (0.004 * (1 + s($rad)))" | bc -l)

    sleep $delay

    ((offset = (offset + 1) % term_width))
    ((frame = (frame + 1) % frames_per_cycle))
done
