#!/bin/bash

set -oue pipefail
shopt -s dotglob

LOOP_DEV=$(losetup -f)
HOME_DIR=/var/home
HOMEFS_DIR=/var/usrlocal/homefs
MAPPER_DIR=/dev/mapper/homefs-decrypted-$PAM_USER
PRODUCT_SKU=$(cat /sys/class/dmi/id/product_sku | tr -d ' ')
GEN_TMPDIRNAME=$(openssl rand -hex 32)

if [[ -d $HOME_DIR/$PAM_USER ]]; then
    if [[ "$1" == "--mount" ]]; then
        if [[ ! -f $HOMEFS_DIR/$PAM_USER.img.homefs ]]; then
            echo "Creating HomeFS image..."
            truncate -s "$(df -h "$HOME_DIR" | awk 'NR==2 {print $2}')" $HOMEFS_DIR/$PAM_USER.img.homefs
            chown $PAM_USER:$PAM_USER $HOMEFS_DIR/$PAM_USER.img.homefs
            chmod 700 $HOMEFS_DIR/$PAM_USER.img.homefs
            echo "Encrypting image..."
            keyctl add user $PRODUCT_SKU-homefs-$PAM_USER "$(openssl rand -base64 12)-$(openssl rand -hex 18)" @u > /dev/null 2>&1
            losetup $LOOP_DEV $HOMEFS_DIR/$PAM_USER.img.homefs
            keyctl search @u user $PRODUCT_SKU-homefs-$PAM_USER | keyctl pipe $(cat /dev/stdin) | cryptsetup --type luks2 --cipher aes-xts-plain64 luksFormat $LOOP_DEV
            keyctl search @u user $PRODUCT_SKU-homefs-$PAM_USER | keyctl pipe $(cat /dev/stdin) | cryptsetup luksOpen $LOOP_DEV homefs-decrypted-$PAM_USER
            mkfs.ext4 $MAPPER_DIR -F
            echo "Mounting..."
            mkdir -p /tmp/homefs-private-$GEN_TMPDIRNAME/
            mount $MAPPER_DIR /tmp/homefs-private-$GEN_TMPDIRNAME/
            echo "Transferring data..."
            mv $HOME_DIR/$PAM_USER/* /tmp/homefs-private-$GEN_TMPDIRNAME/
            rm /tmp/homefs-private-$GEN_TMPDIRNAME/lost+found
            echo "Remounting..."
            umount $MAPPER_DIR
            rmdir /tmp/homefs-private-$GEN_TMPDIRNAME
            mount $MAPPER_DIR $HOME_DIR/$PAM_USER/
            restorecon -RFv $HOME_DIR/$PAM_USER
            echo "Done."
            exit 0
        elif [[ -f $HOMEFS_DIR/$PAM_USER.img.homefs ]]; then
            echo "Unencrypting..."
            losetup $LOOP_DEV $HOMEFS_DIR/$PAM_USER.img.homefs
            keyctl search @u user $PRODUCT_SKU-homefs-$PAM_USER | keyctl pipe $(cat /dev/stdin) | cryptsetup luksOpen $LOOP_DEV homefs-decrypted-$PAM_USER
            echo "Mounting..."
            mkdir -p $HOME_DIR/$PAM_USER/
            mount $MAPPER_DIR $HOME_DIR/$PAM_USER/
            echo "Done."
            exit 0
        else
            echo "Unknown error. Abort."
            exit 0
    elif [[ "$1" == "--umount" ]]; then
        echo "Unmounting..."
        umount $HOME_DIR/$PAM_USER
        rmdir $HOME_DIR/$PAM_USER
        echo "Closing HomeFS device..."
        cryptsetup luksClose homefs-decrypted-$PAM_USER
        losetup -d $LOOP_DEV
        echo "Done."
        exit 0
    else
        echo "No mount arg passed. Abort."
        exit 0
    fi
else
    echo "No such user $PAM_USER, not handling."
    exit 0
fi
