#!/bin/bash

if [[ "$UID" -ne 0 ]]; then
    echo "Error: Not authorized."
    exit 1
fi

set -oue pipefail

mkdir -p /var/usrlocal/{homefs,nixfs/{upper,work}}
chown root:root /var/usrlocal/{homefs,nixfs/{upper,work}}
chmod 700 /var/usrlocal/{homefs,nixfs/{upper,work}}