#!/bin/bash

set -oue pipefail

mkdir -p /var/usrlocal/{homefs,nixfs/{upper,work}}
chown root:root /var/usrlocal/{homefs,nixfs/{upper,work}}
chmod 700 /var/usrlocal/{homefs,nixfs/{upper,work}}

semanage fcontext -a -t etc_t "/usr/nix/store/[^/]+/etc(/.*)?"
semanage fcontext -a -t lib_t "/usr/nix/store/[^/]+/lib(/.*)?"
semanage fcontext -a -t systemd_unit_file_t "/usr/nix/store/[^/]+/lib/systemd/system(/.*)?"
semanage fcontext -a -t man_t "/usr/nix/store/[^/]+/man(/.*)?"
semanage fcontext -a -t bin_t "/usr/nix/store/[^/]+/s?bin(/.*)?"
semanage fcontext -a -t usr_t "/usr/nix/store/[^/]+/share(/.*)?"
semanage fcontext -a -t var_run_t "/usr/nix/var/nix/daemon-socket(/.*)?"
semanage fcontext -a -t usr_t "/usr/nix/var/nix/profiles(/per-user/[^/]+)?/[^/]+"
semanage fcontext -a -t etc_t "/usr/local/nixfs/upper/nix/store/[^/]+/etc(/.*)?"
semanage fcontext -a -t lib_t "/usr/local/nixfs/upper/store/[^/]+/lib(/.*)?"
semanage fcontext -a -t systemd_unit_file_t "/usr/local/nixfs/upper/store/[^/]+/lib/systemd/system(/.*)?"
semanage fcontext -a -t man_t "/usr/local/nixfs/upper/store/[^/]+/man(/.*)?"
semanage fcontext -a -t bin_t "/usr/local/nixfs/upper/store/[^/]+/s?bin(/.*)?"
semanage fcontext -a -t usr_t "/usr/local/nixfs/upper/store/[^/]+/share(/.*)?"
semanage fcontext -a -t var_run_t "/usr/local/nixfs/upper/var/nix/daemon-socket(/.*)?"
semanage fcontext -a -t usr_t "/usr/local/nixfs/upper/var/nix/profiles(/per-user/[^/]+)?/[^/]+"
