#!/bin/bash

hash_dirs() {
    if [[ ! -f $1 ]]; then
        echo "Creating hashfile $1"
        touch $1
        echo "Created hashfile $1"
    else
        while IFS= read -r line; do
            [[ "$line" =~ ^#.*$ ]] && continue
            find "$line" -type f -print0 | sort -z | while IFS= read -r -d '' file; do
                sha256sum "$file"
            done | sha256sum
        done < "$1"
    fi
}

deployment_status() {
    if [[ ! -f /etc/pesticide.d/deployment.hash ]]; then
        touch /etc/pesticide.d/deployment.hash
        echo "$(bootc status | sha256sum)" > /etc/pesticide.d/deployment.hash
    else
        if [[ "$(bootc status | sha256sum)" != "$(cat /etc/pesticide.d/deployment.hash)" ]]; then
            echo "1"
        else
            echo "0"
        fi
    fi
}

if [ ! -f "/etc/pesticide.d/pesticide.conf" ]; then
    echo "Configuration file does not exist."
    exit 1
elif [ "$(deployment_status)" != "0" ]; then
    echo "An update has been applied. Regenerating hashes..."
    if [ -f "/etc/pesticide.d/dirs.hash" ]; then
        rm /etc/pesticide.d/dirs.hash
    fi
    hash_dirs /etc/pesticide.d/dirs.hash
    echo "STATUS=OK" > /etc/pesticide.d/status
    echo "Hashes regenerated."
elif [ ! -f "/etc/pesticide.d/setup_is_done.lock" ]; then
    echo "First run detected, creating hashes..."
    hash_dirs /etc/pesticide.d/dirs.hash
    touch /etc/pesticide.d/setup_is_done.lock
    exit 0
elif [ -f "/etc/pesticide.d/setup_is_done.lock" ]; then
    echo "Checking hashes..."
    hash_dirs /tmp/hash.tmp
    diff /tmp/hash.tmp /etc/pesticide.d/dirs.hash
    if [ $? -eq 0 ]; then
        echo "STATUS=OK"
        echo "STATUS=OK" > /etc/pesticide.d/status
        rm /tmp/hash.tmp
        exit 0
    else
        echo "STATUS=TAINTED"
        echo "STATUS=TAINTED" > /etc/pesticide.d/status
        rm /tmp/hash.tmp
        exit 1
    fi
else
    echo "Unknown error."
    exit 1
fi
